# -*- coding: utf-8 -*-
"""YoutubeTEXT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15PoTARafMHG8-0dNmMKv2bjTIc-UYMqU

#**Program that contains a function to search any youtube video for a specific word , then display the time the word occurs.**
"""

#!pip install youtube_transcript_api
from youtube_transcript_api import YouTubeTranscriptApi
import datetime
def VidWordSearch(vidcode, targetword):
    a=YouTubeTranscriptApi.get_transcript(vidcode)

    obs = []
    obs_strttime = []
    for i in a:
        for j in i:
          if type(i[j]) == str and targetword in (i[j]):
                  obs.append(i[j])

    for i in range(0,len(a)):
        if a[i]['text'] in obs:
            obs_strttime.append(str(datetime.timedelta(seconds=a[i]['start'])))
    return obs_strttime

"""# *Using the function with a podcast searching for occurences of 'talk' displayed in h:m:s:ms format*"""

VidWordSearch('MOtBrCzt-Yo','talk')